apiVersion: apps/v1
kind: Deployment
metadata:
  name: picsrate-ui-dep
  namespace: studio-qa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: picsrate-ui-dep
  template:
    metadata:
      labels:
        app: picsrate-ui-dep
    spec:
      containers:
        - name: picsrate-ui-dep
          image: studio-registry:5000/picsrate-ui:latest
          ports:
            - containerPort: 3000
          env:
            - name: GENERATE_SOURCEMAP
              value: "false"
            - name: REACT_APP_API
              value: "http://picsrate-service"
            - name: REACT_APP_KEYCLOAK_API
              value: "https://auth.qa.picsrate.bbs-studio.tn"