apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: picsrate-ui
  namespace: studio-qa
  annotations:
    ingress.kubernetes.io/ssl-redirect: "true"
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/rule-type: PathPrefix
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
    - hosts:
      - picsrate-ui.bbs-studio.tn
      secretName: picsrate-ui.bbs-studio.tn-tls
  rules:
    - host: picsrate-ui.bbs-studio.tn
      http:
        paths:
          - pathType: Prefix
            backend:
              service:
                name: picsrate-ui-svc
                port:
                  number: 80
            path: /