apiVersion: v1
kind: Service
metadata:
  name: picsrate-ui-svc
  namespace: studio-qa
spec:
  selector:
    app: picsrate-ui-dep
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      