{{- range $key, $val := .Values.frontend }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $key }}-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ $key }}-dep
  template:
    metadata:
      labels:
        app: {{ $key }}-dep
    spec:
      # hostAliases:
      # {{- range  $el := $val.dns }}
      # - ip: {{ $el.ip }}
      #   hostnames:
      #   - {{ $el.host }}
      # {{- end }}    
      containers:
      - image: {{ $val.image }}:{{ $val.tag }}
        imagePullPolicy: Always
        name: {{ $key }}
        env:
        - name: GENERATE_SOURCEMAP
          value: "false"
        - name: REACT_APP_API
          value: {{ $val.backend_url }}
        - name: REACT_APP_KEYCLOAK_API
          value: {{ $val.keycloak_url }}
        - name: REACT_APP_KEYCLOAK_REALM
          value: {{ $val.keycloak_realm }}
        - name: REACT_APP_KEYCLOAK_CLIENT
          value: {{ $val.keycloak_client }}
        ports:
          - name: http
            containerPort: {{ $val.target_port }}
            protocol: TCP
{{- end }}