{{- range $key, $val := .Values.frontend }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $key }}-svc
spec:
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: {{ $key }}-dep

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: picsrate-ui
  namespace: studio-qa
  annotations:
    ingress.kubernetes.io/ssl-redirect: "true"
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/rule-type: PathPrefix
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
    - hosts:
      - {{ $val.host }}
      secretName: {{ $val.host }}-tls
  rules:
    - host: {{ $val.host }}
      http:
        paths:
          - pathType: Prefix
            backend:
              service:
                name: {{ $key }}-svc
                port:
                  number: 80
            path: /
{{ end }}
