name: GitHub Actions Demo
run-name: "${{ github.actor }}: ${{ inputs.environment }} -  ${{ github.run_number }}"
on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: pick environment
        default: dev
        options:
          - dev
          # - qa
          # - prod

jobs:
  run-project-tests:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3

      - name: Create environment file
        run: |
          echo "VERSION=$(cat version.json | jq -r .version | sed -r "s/[x]+/${{ github.run_number }}/g")" >> $GITHUB_ENV
      - name: Plot inputs
        run: |
          echo "environment is ${{ inputs.environment }}"
      - name: Install dependencies
        run: npm install
      - name: Run Picsrate Tests
        run: npm test
      - name: Build and tag Docker image
        run: |
          docker build -t picsrate-ui:latest . 
          docker tag picsrate-ui:latest studio-registry:5000/picsrate-ui:latest
          docker push studio-registry:5000/picsrate-ui:latest